music.playTone(831, music.beat(BeatFraction.Half))
music.playTone(523, music.beat(BeatFraction.Whole))
music.playTone(831, music.beat(BeatFraction.Half))
music.playTone(831, music.beat(BeatFraction.Whole))
music.playTone(523, music.beat(BeatFraction.Double))
music.playTone(523, music.beat(BeatFraction.Half))
music.playTone(554, music.beat(BeatFraction.Whole))
music.playTone(523, music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Half))
music.playTone(523, music.beat(BeatFraction.Whole))
music.playTone(784, music.beat(BeatFraction.Half))
music.playTone(784, music.beat(BeatFraction.Whole))
music.playTone(523, music.beat(BeatFraction.Double))
music.playTone(466, music.beat(BeatFraction.Half))
music.playTone(523, music.beat(BeatFraction.Whole))
music.playTone(466, music.beat(BeatFraction.Half))
music.playTone(277, music.beat(BeatFraction.Half))
music.playTone(415, music.beat(BeatFraction.Whole))
music.playTone(698, music.beat(BeatFraction.Half))
music.playTone(698, music.beat(BeatFraction.Whole))
music.playTone(415, music.beat(BeatFraction.Double))
music.playTone(415, music.beat(BeatFraction.Half))
music.playTone(466, music.beat(BeatFraction.Whole))
music.playTone(415, music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.playTone(659, music.beat(BeatFraction.Half))
music.playTone(659, music.beat(BeatFraction.Whole))
music.playTone(392, music.beat(BeatFraction.Double))
music.playTone(698, music.beat(BeatFraction.Whole))
music.playTone(784, music.beat(BeatFraction.Whole))
music.playTone(659, music.beat(BeatFraction.Whole))
music.playTone(698, music.beat(BeatFraction.Whole))
basic.forever(function () {
	
})
